name: Enrich Release
on:
  release:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: bruceadams/get-release@v1.2.1
      id: get_release
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: |
        cd app
        npm --no-git-tag-version version ${{ steps.get_release.outputs.tag_name }}
        npm run ci-release
        cd ../worker
        npm --no-git-tag-version version ${{ steps.get_release.outputs.tag_name }}
        npm run ci-release
        cd ..
        mkdir -p dist/web
        cp --recursive --parents index.html app/index.html app/favicon.ico app/images app/styles app/dist/browser/browser.js worker/worker.js worker/dist/browser/browser.js dist/web
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: |
        cd dist/web
        zip -r ../web.zip .
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./dist/web.zip
        asset_name: cube-codes-ide-${{ steps.get_release.outputs.tag_name }}-web.zip
        asset_content_type: application/zip
    - run: |
        cd app/dist/docs
        zip -r ../docs.zip .
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./app/dist/docs.zip
        asset_name: cube-codes-ide-${{ steps.get_release.outputs.tag_name }}-app-docs.zip
        asset_content_type: application/zip
    - run: |
        cd worker/dist/docs
        zip -r ../docs.zip .
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./worker/dist/docs.zip
        asset_name: cube-codes-ide-${{ steps.get_release.outputs.tag_name }}-worker-docs.zip
        asset_content_type: application/zip
    - run: |
        cd worker/dist/editor-docs
        zip -r ../editor-docs.zip .
    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./worker/dist/editor-docs.zip
        asset_name: cube-codes-ide-${{ steps.get_release.outputs.tag_name }}-editor-docs.zip
        asset_content_type: application/zip
    - uses: actions/checkout@v2
      with:
        ref: web
        path: web
    - run: |
        cd web
        rm --recursive *
        cp --recursive ../dist/web/* .
        cp --recursive ../worker/dist/editor-docs .
        echo 'ide.cube.codes' > CNAME
        git config --global user.name 'CI'
        git config --global user.email 'info@cube.codes'
        git add .
        git commit -am "Set to release ${{ steps.get_release.outputs.tag_name }}"
        git push